### PR TITLE
latest chatgpt-4 preview model for increased token window size

### PR DESCRIPTION
**Pull request by star-3gg**
Idk if this goes against your intentions for the plugin since i only recently stumbled on it but i think it would be cool if there was a way for developers to also use the newer chatgpt-4 models since it allows for pretty big prompts and is very fast too.

Ignore this pull request if chatgpt-4 usage is not intended.

### CODE REVIEW

**Comment by technophile-04** [comment]
++ for this 

also thanks @star-3gg for the PR, planning to use your fork 🙌

**Comment by jackMort** [comment]
Hi, we should switch to new model but what do you think about using: `gpt-4` as default ?

**Comment by star-3gg** [comment]
> Hi, we should switch to new model but what do you think about using: `gpt-4` as default ?

I think that is a great idea as well, I experimented with the preview model to see how the response speed would be.

:+1:

**Comment by Aaronik** [comment]
I'm already doing this in the normal config, why does it need to be defaulted? Doesn't still not everyone have access to that model?

**Comment by star-3gg** [comment]
Hey, I had an idea just now. Wouldn't it be great to have the user select a model during the installation / setup? This way nobody is limited or left out

**Comment by Aaronik** [comment]
During use IMO - I like to use 3.5 for most questions, and 4 for the tricky stuff. Keeps costs down and speed up

**Comment by star-3gg** [comment]
That's a very good point

**Pull request closed without merging**
