### PR TITLE
Make several highlights configurable

### PR DESCRIPTION
**Pull request by petobens**

### CODE REVIEW

**Review by jackMort — APPROVED** [review]

**Comment by petobens** [comment]
Hi @jackMort thanks for the approval. Do we need to fix that stylua check or can this be merged as it is?

**Comment by jackMort** [comment]
Please fix stylua issues

**Comment by petobens** [comment]
I think the last commit should fix it (but I cannot see the workflow run)

**Comment by petobens** [comment]
In the last commit I've also made the code edit results tite configurable.

**Comment by dsully** [comment]
+1 - can others be made configurable as well? I'd like to change `ChatGPTTotalTokensBorder` and `ChatGPTTotalTokens`, but those are set in `.setup()`

Thanks!

**Pull request merged**
