### PR TITLE
Attempt # 2 to fix #352

### LINKED ISSUE #352: <Tab> No longer moves cursor across panes in edit with instructions view
It appears that 1f69ba297388bccc604a76d9c940cb26156c5cd1 broke <Tab> moving the cursor from window to window.

### PR DESCRIPTION
**Pull request by Aaronik**
@jackMort @Moerliy here's another fix that fixes this bug in all invocations of the window, not just the first one, which yesterday's fix addressed.

It also renames one local variable for clarity.

---

The previous fix (#388) worked _only for the first time the edit with instructions window was opened_.

Now it works every time it's opened (at least up to however many times I tested it. Theoretically it could fail on the 10,000th time.)

### CODE REVIEW

**Comment by Moerliy** [comment]
Looks good to me. I have no running instance of nvim currently tho. So I haven't tested it locally. 
If I get the chance to do so I will edit this comment.

**Comment by v3ceban** [comment]
Thanks so much for working on it!

The bug also seems to be present in Optimize and Summarize windows (perhaps other windows too if there are more that I'm unaware of)

**Comment by Aaronik** [comment]
@v3ceban this seems to fix those as well, if my testing is correct. Can you test it out as well?

**Comment by v3ceban** [comment]
@Aaronik indeed, this pr solves the problem in other windows/popups too. Tested on Fedora 39 (x86_64) and Android/Termux (arm).
Thanks for your contribution <3 Hope to see this merged soon!

**Comment by Moerliy** [comment]
Works on:
* M1 MacOS
* Fedora 39 (ARM)
* Arch (ARM)
* Ubuntu 18 (x86_64)
* Ubuntu 23 (ARM)

**Comment by Aaronik** [comment]
@jackMort think this passes muster?

**Comment by Aaronik** [comment]
@jackMort if there's anything wrong with this, please let me know and I'll change it up :+1:

**Review by jackMort — APPROVED** [review]

**Pull request merged**
