### PR TITLE
fix: add close keymap to edit windows (#172)

### PR DESCRIPTION
**Pull request by shutils**
issue #172 

I have added a key map for closing the edit window.

### CODE REVIEW

**Comment by ariel-frischer** [comment]
Nice, was looking for this.

**Comment by jackMort** [comment]
are you able to solve conficts?

**Comment by shutils** [comment]
I rebase to the latest branch and then check the code.

**Comment by shutils** [comment]
@jackMort 

In the latest main branch, there was already code that mapped the close key to the edit window, so I changed it to extend the window it applies to.

**Review by jackMort — APPROVED** [review]

**Pull request merged**
