### PR TITLE
Allow the ChatGPTEditWithInstructions command to accept a range

### LINKED ISSUE #29: Can't get ChatGPTEditWithInstructions to work with text selected in visual mode
Vim says 'no range allowed' but it will run with no text selected and run on the last text you selected, but only once you have deselected it.

### PR DESCRIPTION
**Pull request by Akeboshiwind**
Fixes #29

### CODE REVIEW

**Comment by DGmip** [comment]
Lovely, have been waiting for this to be merged in for a while now, wondering how people have been managing to use ...WithInstructions without this...

**Comment by Akeboshiwind** [comment]
@DGmip If you want to get it working in the meantime, you can use a custom keybind that calls `require("chatgpt").edit_with_instructions()`.

For an example look at my comment [here](https://github.com/jackMort/ChatGPT.nvim/issues/29#issuecomment-1379463692).

**Comment by DGmip** [comment]
Nice one have done so

**Comment by aweis89** [comment]
LGTM!

**Comment by aweis89** [comment]
Still getting `E481: No range allowed` when using the fork

**Comment by kalkin** [comment]
Or just bind the key like this:
vmap <silent> <leader>aa :<C-U>:ChatGPTEditWithInstructions<CR>

**Comment by 00sapo** [comment]
@jackMort why don't you merge this?

**Comment by 00sapo** [comment]
@Akeboshiwind could you update the readme? Right now I inserted a mention to map the function

**Pull request closed without merging**
