### PR TITLE
Make it compatible with windows 

### PR DESCRIPTION
**Pull request by eyalk11**
Added @[zalgo3](https://github.com/jackMort/ChatGPT.nvim/commits?author=zalgo3)
commit as well.

### CODE REVIEW

**Review by jackMort — APPROVED** [review]

**Comment by jackMort** [comment]
thanks, please just fix the style issues to pass checks: https://github.com/jackMort/ChatGPT.nvim/actions/runs/4672213218/jobs/8283131691?pr=148

**Comment by jackMort** [comment]
@eyalk11 could you please fix small styling issues https://github.com/jackMort/ChatGPT.nvim/actions/runs/4672213218/jobs/8283131691?pr=148

**Comment by eyalk11** [comment]
Sorry, this tiny task got complicated. I accidently changed the wrong commit.  Will do it tomorrow. It wasn't that smart not to open a branch dedicated for it. I will probably just open a new pull request.

**Comment by eyalk11** [comment]
OK, so hopefully everything will work now.

**Pull request merged**
